### ISSUE TITLE
Get all tests passing on Appveyor (Windows CI)

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#137]
https://ci.appveyor.com/project/jacebrowning/gitman

**Comment by StudioEtrange** [comment]
Ohhhh
Could you provide the exact setting of the windows CI environment ?

some weird things happen, like os.name seems to not be 'nt'

**Comment by jacebrowning** [comment]
Does any of this help?

- https://www.appveyor.com/docs/installed-software/#operating-system
- https://www.appveyor.com/docs/environment-variables/

**Comment by jacebrowning** [comment]
Maybe it should check `platform.system() == 'Windows'`?

**Comment by StudioEtrange** [comment]
Ok I think i got the problem.
I try to fix it.
It's relative to Config class and some method which return non normalized path AND to Config Unit Test

**Comment by StudioEtrange** [comment]
For my information, how did you generated the Makefile ?
By hand or with autogen or something ?

I have to change some command like "dot" and "find" for windows

**Comment by jacebrowning** [comment]
I generate all my projects using this: https://github.com/jacebrowning/template-python

I'd greatly appreciate suggestions to make that work better on Windows.

**Comment by StudioEtrange** [comment]
Ok, so you copy from this template project the Makefile ?

**Comment by StudioEtrange** [comment]
Ok, you generate a Makefile from this template
https://github.com/jacebrowning/template-python/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/Makefile
?

**Comment by jacebrowning** [comment]
Yes, using https://github.com/audreyr/cookiecutter.

**Comment by jacebrowning** [comment]
I think I will rewrite the portion that calls `find` to use a `python -c` call.

**Comment by StudioEtrange** [comment]
Ok
PR#140 is almost done.

But I am stuck with some pep/pylint guideline.

Need help

**Comment by StudioEtrange** [comment]
After a lot of commit, I finally managed to pass CI guidelines (pep, pylint)

So, work is done on the PR #140 

Need your review.
