### ISSUE TITLE
Support symlinks on Windows

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#147]
Currently symlink support is disabled on Windows:

- https://github.com/jacebrowning/gitman/blob/3dabc3fe0e2093adec3e7a84c2b99540db3ba1e5/gitman/shell.py#L73
- https://github.com/jacebrowning/gitman/blob/3dabc3fe0e2093adec3e7a84c2b99540db3ba1e5/gitman/models/source.py#L96

If anyone would like this feature and understands the syntax for `mklink`, feel free to create a PR.

**Comment by 4O4** [comment]
@jacebrowning  Can [`os.symlink()`](https://docs.python.org/3/library/os.html#os.symlink) be used for that?

**Comment by jacebrowning** [comment]
Possibly. I don't have a Windows machine to test on, but you're welcome to try!

**Comment by daniel-brosche** [comment]
Seems the right way to achieve a crossplatform solution.

@4O4 Did you try this approach on windows?

Some information about the symlink-Feature:

https://docs.python.org/3/library/os.html#os.symlink

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by jacebrowning** [comment]
Added in https://github.com/jacebrowning/gitman/pull/200
