### ISSUE TITLE
git svn support

### ISSUE THREAD

**Issue by daniel-brosche** [jacebrowning/gitman#151]
I'm thinking to implement a readonly import of svn dependencies by using [git-svn](https://git-scm.com/docs/git-svn). The basic idea is, to analyze the passed url to the git.py module to decide if the git-svn should be used instead of the basic git commands. What do you think about that?

**Comment by jacebrowning** [comment]
Which of the functions in `git.py` would be affected?

**Comment by daniel-brosche** [comment]
git.clone and git.update

**Comment by jacebrowning** [comment]
That sounds fine. Please add unit tests for the modified functions.
