### ISSUE TITLE
feature request: support npm / pnpm / yarn / composer

### ISSUE THREAD

**Issue by DanielRuf** [jacebrowning/gitman#172]
Yarn, npm, composer and so on have json files which can reference and use Git URLs (https, git, ssh).
It could be useful to read the needed dependencies from them and use these + the needed directories (vendor, node_modules and so on) to manage them.

**Comment by jacebrowning** [comment]
I'm not sure I understand this request. The whole point of this project is to support dependencies referenced via Git URLs. Can you point me to an example?

**Comment by DanielRuf** [comment]
The point is to also read / migrate from existing projects which have a package.json or composer.json.

Or is this out of the scope of gitman and should we do this manually?

**Comment by jacebrowning** [comment]
I would consider this out of scope for now unless someone comes forward with an implementation. ✌️
