### ISSUE TITLE
new releases needed

### ISSUE THREAD

**Issue by DanielRuf** [jacebrowning/gitman#173]
The last release was many months ago.

**Comment by jacebrowning** [comment]
I can get that started. Have you tested the 1.5 beta releases with your projects?

**Comment by DanielRuf** [comment]
Not yet, was planned for this weekend when I have some more time.

**Comment by jacebrowning** [comment]
I just released `pip install gitman==1.5b4` that will contain every change planned for the next release.

**Comment by jacebrowning** [comment]
I released 1.5 today!
