### ISSUE TITLE
Add '--force-interactive' to select which changes to overwrite

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#174]
In a large project, multiple dependencies might require forced-installation, but the user should have to confirm this each time.

**Comment by daniel-brosche** [comment]
Should this be realized by a new option like `--force-interactive`?

**Comment by jacebrowning** [comment]
Yeah, I like that suggestion!

**Comment by jacebrowning** [comment]
Added in https://github.com/jacebrowning/gitman/pull/197
