### ISSUE TITLE
Possible Feature Request - Nested Dependencies Organization

### ISSUE THREAD

**Issue by andarilhoz** [jacebrowning/gitman#175]
# Problem
Hi, i don't really know if this is already done, but i could'nt found anything on the documentation, on the issues open and close, so here it goes:

When having nested dependencies, gitman install everything inside current gitman.yml location path, relative to the current dependency, that lead to two behaviours:

 ### Confusing working tree

With two or more nested dependencies, the working tree starts looking a little messy

### Redundant dependencies

When both projects have identical dependencies, it is downloaded twice, on compiled languages, that leads to an "Namespace X already contains a definition for Y"

# Possible Solution

Over confusing working trees, gitman could do something similar to NPM behaviour, nesting all dependecies under the first root, inside another folder with the project name

e.g.
node_modules/
├── foo/
│   └── node_modules/
│       ├── hello/
│       └── world/
└── bar/
    └── node_modules/
        ├── hello/
        └── goodbye/

I really dont know how to solve the redundant dependencies problem, maybe setting it on a config file, i don't know.

**Comment by jacebrowning** [comment]
I think this is the same request as https://github.com/jacebrowning/gitman/issues/128, please confirm. 😄

**Comment by andarilhoz** [comment]
@jacebrowning  That's completly right! don't know how i missed that out.

Thank you, i'll follow that request 😄
