### ISSUE TITLE
optional disabling of the gitcache

### ISSUE THREAD

**Issue by daniel-brosche** [jacebrowning/gitman#178]
I have an use case where the gitcache is not a good thing. 
This [article](https://randyfay.com/content/git-clone-reference-considered-harmful) describes in which scenarios gitcache can be probelmatic (the point 2-3 are really a problem in one of my use cases).
Therefore I need an option to disable caching over an option.

What do you think?

**Comment by jacebrowning** [comment]
I think we could add a new environment variable (https://gitman.readthedocs.io/en/latest/setup/environment/) called `GITMAN_CACHE_DISABLE`. If set, repositories will be cloned directly.

**Comment by daniel-brosche** [comment]
Ok, I will try that

**Comment by daniel-brosche** [comment]
What are your typical  development steps to verify your development stage locally. Actualy I currently install the development-stage globally by using the setup.py and then trying to debug (because in my mind gitman recursively calls gitman which needs to be system-wide installed). Is there a smarter way to do that?

**Comment by jacebrowning** [comment]
Check out how `$ make demo` is implemented. That will run the local version of gitman.

**Comment by daniel-brosche** [comment]
Why is yorm listed in pipfile.lock and not in the pipfile itself?
Is this correct?

**Comment by jacebrowning** [comment]
Yeah, that's correct. The runtime dependencies are pulled in from [`setup.py`](https://github.com/jacebrowning/gitman/blob/develop/setup.py).

Eventually I'll switch this project over to [poetry](https://github.com/sdispater/poetry), which make a lot more sense for libraries.

**Comment by daniel-brosche** [comment]
Good to know. Poetry looks nice and clean...
