### ISSUE TITLE
Add a '--skip-changes' option to 'update'

### ISSUE THREAD

**Issue by daniel-brosche** [jacebrowning/gitman#181]
The current behaviour is that an update command does sequentially iterate though the gitman.yml and updates all repositories if there are no uncommited changes present. If gitman detects a repository with uncommited changes then the update process will be aborted with an message and all successor repositories in the list won't be updated. 
If the first defined repository in the gitman.yml has uncommited changes then the majority of the defined repositories won't be updated.

The `--skip-changes` option allows to update all repositories besides the repositories with uncommited changes. At the end of the process the user gets a summary which repositories are ignored in due to uncommited changes. A special return code in this case should be considered.

Maybe, this option is a candidate to be the default behaviour of `gitman update` command and instead an option `--abort-changes` should be introduced to activate the current behaviour.

**Comment by jacebrowning** [comment]
I'm in favor of adding a `--skip-changes`option to both `install` and `update` as part of this parser: https://github.com/jacebrowning/gitman/blob/9b9c715f636ec0f2d03167b1d92862fadb7faf11/gitman/cli.py#L33-L37

If changes are detected, this new option should also be recommended: https://github.com/jacebrowning/gitman/blob/9b9c715f636ec0f2d03167b1d92862fadb7faf11/gitman/cli.py#L190-L192
