### ISSUE TITLE
Support for git parameters e.g. --depth 1

### ISSUE THREAD

**Issue by wildi1** [jacebrowning/gitman#206]
I'm new to gitman and i really like this project. For projects where you have got very big dependencies with a lot of branches it would be very nice when you could give for example a depth like "git clone xyz --depth 1" so that your repository will clone only the last commit.
-------------------------------
location: vendor/gitman
sources:
- name: framework
  repo: https://github.com/kstenerud/iOS-Universal-Framework
  rev: Mk5-end-of-life 
  clone-depth:1

Another possible solution would be to give extra parameters to the clone command like:
--------------------------------
location: vendor/gitman
sources:
- name: framework
  repo: https://github.com/kstenerud/iOS-Universal-Framework
  rev: Mk5-end-of-life
  clone-params:
  - depth 1
  - ...

I would also make a Pull Request for this issue, but before I would like to ask you if you are open for that, or what your opinion to this request is.

**Comment by jacebrowning** [comment]
Does this necessarily need to be part of the configuration or would a CLI option also work for your use case?

**Comment by wildi1** [comment]
First of all, thank you for your very fast answer. When it is easier to implement a CLI option, than I think it would also work for my use case. Then I can use the groups option, to separate which repositories will be cloned with e.g. depth 1 and which get fully cloned. So in this case I have to run gitman also just two times. That would be great ;-)

**Comment by klaxalk** [comment]
Hello, I second this suggestion, it would be very beneficial. I also think that the per-group or per-repository option is a good idea. Thanks

**Comment by brandonaut** [comment]
The ability to customize the git command would be very helpful for running in a CI context. For example, to set different credentials for different submodule clones, I need to be able to call git with one-time config options: `git -c [some configuration options] submodule update --init --remote`.
