### ISSUE TITLE
Allow dirty during list

### ISSUE THREAD

**Issue by marcellodesales** [jacebrowning/gitman#207]
Why wouldn't the CLI not show list of dependencies when the dir is `dirty`?

```console
$ docker run --rm -it  \
    -v $(pwd):/project \
    -v $HOME/.ssh:/.ssh marcellodesales/gitman:1.7 list
Change directory into '/project'

Displaying current dependency versions...

$ cd /project/gitman_sources

  $ cd sample_dependency
  $ git diff-index --quiet HEAD
  <dirty>
```

So the list of files are NOT even related... Isn't the only relevant dir in question `gitman_sources/`? 

```console
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
	modified:   cmd/dependencies.go
	modified:   cmd/generate.go
	modified:   cmd/init.go
	modified:   cmd/publish.go
	modified:   cmd/root.go
	modified:   cmd/validate.go
	deleted:    main.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.idea/
	gitman.yml
	gitman_sources/
	protocool-logo-smaller.png
	protocool-logo.png
	protocool.go
```

# Add `allow-dirty` to list

* I would like to have a switch to allow-dirty no matter if the dir is related or not...

**Comment by jacebrowning** [comment]
Sorry, I'm not following your question. The purpose of `list` is to display the current commit SHA for each dependency. If a dependency's working tree has changes we can not identify it, so display "dirty".

**Comment by marcellodesales** [comment]
@jacebrowning But doesn't gitman have the record of the pulled versions of all ?

**Comment by marcellodesales** [comment]
I just want to show the current version originally pulled...

**Comment by jacebrowning** [comment]
For that, I would recommend simply viewing the configuration file to see what version was originally checked out.
