### ISSUE TITLE
gitman command not found

### ISSUE THREAD

**Issue by jingxixu** [jacebrowning/gitman#210]
My default python is 2.7 so I installed gitman with `pip3 install gitman` and it is successfully installed. However, we I run `gitman install` it says gitman command not found and `python3 -m gitman install` works. 

Many thanks!

**Comment by jacebrowning** [comment]
Hi @jingxixu! Unfortunately I can't help you debug the way your computer is set up. Presumably you're experiencing this issue with all Python 3 programs, so it's not specific to `gitman`.

I recommend `pipx` for managing installed Python programs: https://pipxproject.github.io/pipx/
