### ISSUE TITLE
Better verbosity for scripts

### ISSUE THREAD

**Issue by spurnvoj** [jacebrowning/gitman#217]
Imagine that you are running for instance `git submodule update --init --recursive --depth 1` for repository with a large number of submodules. In our case, this usually takes a couple of minutes to download (depends on the internet connection) and Gitman displays the processed commands after the command is processed, making the user consider if the system has hanged. It would be great if the output was displayed in real time, or at least updated regularly.

**Comment by jacebrowning** [comment]
This change is available in `gitman==2.1b1`.
