### ISSUE TITLE
sparse_paths handling

### ISSUE THREAD

**Issue by OV2** [jacebrowning/gitman#218]
I encountered two issues when trying sparse_paths with gitman:

(this is on windows with miniconda and GitMan v2.0, but I think there have been no relevant changes since then)

### Multiple sparse_paths entries
Having multiple sparse_paths entries in gitman.yml results in one line in sparse-checkout.
Example:
```
    sparse_paths:
      - Test/*
      - Tools/*
```
results in a sparse-checkout file containing
```
Test/*Tools/*
```
It looks like changing the [corresponding line](https://github.com/jacebrowning/gitman/blob/8e27959639128f7fba6798f097f91e8212b57bf2/gitman/git.py#L55) in git.py to something like
```
fd.writelines(["%s\n" % item  for item in sparse_paths])
```
fixes this. I'm not versed enough in python to decide if that's appropriate, thus no pull request.

### Updating sparse_paths entries
It looks like at the moment the sparse_paths entries are only written during the initial cloning. So if we later decide we need more files from a repo, we can not simply update the gitman.yml file and do an update, we need to either delete the repo first, or manually update the sparse-checkout file.

**Comment by kevinv92** [comment]
Just arrived on this issue as well. The fix suggested for sparse_checkout seems pretty straightforward. Maybe `"\n".join(sparse_paths)` but it basically solves the same issue.

Worked around the issue by configuring sparse_paths items with a newline at the end:
```yaml
  ...
   sparse_paths:
     - "path1/*\n"
     - "path2/*\n"
```

Hopefully above is enough to unblock anyone else who reached this issue.
