### ISSUE TITLE
Uninstall should delete dependencies by path

### ISSUE THREAD

**Issue by brandonaut** [jacebrowning/gitman#227]
It seems that `gitman uninstall` currently deletes everything in the `location` directory. This is problematic when GitMan is used like traditional submodules, where the dependencies are interspersed with the native folders (e.g, `location: .`). In that situation, running `gitman uninstall` will delete the entire local repo, not just the dependencies.

Instead, `gitman uninstall` should delete each dependency listed in `gitman.yml` individually by name (concatenated with `location`), rather than doing a single delete at the top-level `location`.

**Comment by jacebrowning** [comment]
Thanks for the suggestion!

A quick workaround could be to bail early if location is `.` to prevent deletion of the whole project. 😱
