### ISSUE TITLE
Document every field available in configuration files

### ISSUE THREAD

**Issue by SamMousa** [jacebrowning/gitman#261]
It seems there is no reference to what keys are usable inside a config file, am I looking in the wrong place or is there no such reference?

**Comment by jacebrowning** [comment]
The example config on https://gitman.readthedocs.io/ shows all possible options, which are then mentioned in relevant sections:

- https://gitman.readthedocs.io/en/latest/use-cases/submodules/
- https://gitman.readthedocs.io/en/latest/use-cases/sparse-checkouts/
- https://gitman.readthedocs.io/en/latest/use-cases/default-groups/
- etc.

Is there a particular option you feel is not mentioned? Or would a dedicated config section in the docs be helpful?

**Comment by SamMousa** [comment]
Scripts for example.

It is mentioned but has no docs.

**Comment by jacebrowning** [comment]
The first pass at this documentation is here: https://gitman.readthedocs.io/en/latest/setup/configuration/

Folks should feel free to add whatever they feel would be helpful!
