### ISSUE TITLE
find_nested_configs does not use depth value or find depth > 2 packages

### ISSUE THREAD

**Issue by DavidWatkins** [jacebrowning/gitman#294]
Issue:
The function `find_nested_config` in `gitman/models`config.py` does not incorporate the `depth` variable except to check if it should do a 1 level shallow search. 

Proposal:
Update the function to use `depth` to appropriately search the entire repository up to that level. Any objections to me making a PR for this?

**Comment by jacebrowning** [comment]
@DavidWatkins yeah that sounds good to me!

**Comment by jacebrowning** [comment]
This fix for this is published here: https://pypi.org/project/gitman/3.3.2/
