### ISSUE TITLE
filter_nested_configs is doing the opposite of what it should

### ISSUE THREAD

**Issue by davidwatkins-bdai** [jacebrowning/gitman#311]
When I introduced `filter_nested_configs`, I had meant to filter out any `gitman.yml` files that were present inside of the top-level config file. This requires more intelligently filtering any nested `gitman.yml` files that are present in already `gitman install`'d dependencies. This requires changing `filter_nested_configs` in `$PROJECT_ROOT/models/config.py` to:
```python
def filter_nested_configs(
    configs: List[Config]
) -> List[Config]:
    """Filter subdirectories inside of parent config."""
    filtered_configs = []
    for config_a in configs:
        is_nested = False
        for config_b in configs:
            if config_a == config_b:
                continue
            if Path(config_b.location_path) in Path(config_a.location_path).parents:
                is_nested = True
                break
        if not is_nested:
            filtered_configs.append(config_a)

    return filtered_configs
```

And also modifying L91-L95 in `$PROJECT_ROOT/gitman/commands.py` to:
```python
...
    config = load_config(root)
    configs = [config] if config else []
    configs.extend(find_nested_configs(root, depth, []))
    configs = filter_nested_configs(configs)
...
```

**Comment by davidwatkins-bdai** [comment]
I have this account for doing work-related activities and now I am making these adjustments using this one. I'll make the PR with my old account.

**Comment by jacebrowning** [comment]
This beta release contains the fix for this issue: https://pypi.org/project/gitman/3.4.1b1/
