### ISSUE TITLE
Reattach HEAD if revision is locked

### ISSUE THREAD

**Issue by davidwatkins-bdai** [jacebrowning/gitman#320]
Currently, if you lock a revision that there is no branch on, the repository will be cloned in a detached state. Can we add a flag to reattach HEADs automatically?

**Comment by jacebrowning** [comment]
Is this request related to https://github.com/jacebrowning/gitman/issues/74 or something different? It would be helpful if you could provide exact `git` commands to get a working copy of https://github.com/jacebrowning/gitman-demo into the state you're describing.

**Comment by ggoretkin-bdai** [comment]
@jacebrowning yup! That's exactly the issue @davidwatkins-bdai and I are talking about. (Sorry for the delay.)

**Comment by jacebrowning** [comment]
OK, in that case I'm going to close this a duplicate and we can continue the conversation on #74.
