### ISSUE TITLE
Add a way to install a specific dependency version from the CLI

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#98]
Something like:
- `gitman install foo@0bcd85a`
- `gitman install foo -r 0bcd85a`
- `gitman install foo:0bcd85a`
- `gitman install foo --at 0bcd85a`

**Comment by jacebrowning** [comment]
Or perhaps it could be a two-step process:

```
gitman save foo 0bcd85a
gitman install
```

**Comment by jacebrowning** [comment]
This could also support adding new sources:

```
$ gitman save https://github.com/owner/<name>@<rev>
```

**Comment by Erich-McMillan** [comment]
@jacebrowning I have a need for this feature. Has any work been done since this initial feature request was opened? Otherwise I'll start working on implementing the feature.

**Comment by jacebrowning** [comment]
@Erich-McMillan No, I don't think so. Have at it!

I think this feature should mimic [Poetry](https://python-poetry.org/docs/cli/) as much as possible.

## Add (and Install)

```
gitman add https://github.com/foo/bar         # `rev` unset to default to 'main'
gitman add https://github.com/foo/bar@abc123  # `rev` set to 'abc123'
```

## Update
```
gitman update bar         # existing update behavior
gitman update bar@abc123  # `rev` set to 'abc123' then do update
```

---

Perhaps each of these could be separate PR if you want early feedback:

1. `gitman update bar@abc123`
2. `gitman add https://github.com/foo/bar`
3. `gitman add https://github.com/foo/bar@abc123`

**Comment by jacebrowning** [comment]
1️⃣ was implemented in https://github.com/jacebrowning/gitman/pull/274

**Comment by jacebrowning** [comment]
I moved the reset of this ticket to https://github.com/jacebrowning/gitman/issues/279.
